defaults:
  - _self_
  - compute: slurm # must be slurm or local
  - exp: ???

base_output_dir: /scratch/anw2067/greene-utility/experiments
experiment: ???
name: ???

hydra:
  job:
    name: ${name}
  callbacks:
    log_job_return_callback:
      _target_: submitit_hydra.LogJobReturnCallback
    
